#spring:
#  application:
#    name: vidhyaleBox
#
#
#
#  datasource:
#    url: jdbc:postgresql://34.47.249.112:5432/vidhyalebox
#    username: postgres
#    password: Pass@1812
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#
#logging:
#  level:
#    org.springframework.security: DEBUG

spring:
  application:
    name: vidhyaleBox

  datasource:
    url: jdbc:mysql://localhost:3306/vidhyalebox
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
