#spring:
#  application:
#    name: vidhyaleBox
#
#
#
#  datasource:
#    url: jdbc:postgresql://34.47.249.112:5432/vidhyalebox
#    username: postgres
#    password: Pass@1812
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#
#logging:
#  level:
#    org.springframework.security: DEBUG

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: mail
    password: pwd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
  application:
    name: vidhyaleBox

  datasource:
    url: jdbc:mysql://localhost:3306/vidhyalebox
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG

image:
  storage:
    path: D://